export const ROUTERS = {
  HOME: '/',
  FORBIDDEN: '/forbidden',
  LOGIN: '/login',
  USER_MANAGEMENT: '/user-management',
  AUDIT_LOG: '/audit-logs',
  SETTINGS: '/settings',
  INSTITUTION: '/settings/institution',
  SSO_CONFIGURATION: '/settings/sso-configuration',
  REVIEW_EXTRACTION: '/review-extraction',
  DOCUMENT_RETENTION: '/document-retention',
  RETENTION_POLICY: '/retention-policy',
  UPLOAD_DOCUMENT: '/review-extraction/upload-document',
  REVIEW_EXTRACTION_VENDOR: (vendor: string) => `/review-extraction/${encodeURIComponent(vendor)}`,
  REVIEW_EXTRACTION_VENDOR_ID: (vendor: string, id: string) => `/review-extraction/${encodeURIComponent(vendor)}/${id}`,
  ANALYSIS: '/analysis',
  ANALYSIS_VENDOR: (vendor: string) => `/analysis/${encodeURIComponent(vendor)}`,
  FINANCIAL_ANALYSIS_VENDOR_ID: (vendor: string, id: string) => `/analysis/${encodeURIComponent(vendor)}/${id}/financial-statement`,
  BANK_STATEMENT_ANALYSIS_VENDOR_ID: (vendor: string, id: string) => `/analysis/${encodeURIComponent(vendor)}/${id}/bank-statement`,
  COMBINED_ANALYSIS_VENDOR_ID: (vendor: string, id: string) => `/analysis/${encodeURIComponent(vendor)}/${id}/combined-analysis`,
  FRAUD_DETECTION_VENDOR_ID: (vendor: string, id: string) => `/analysis/${encodeURIComponent(vendor)}/${id}/fraud-detection`,
  CONSOLIDATED_ANALYSIS_VENDOR_ID: (vendor: string, id: string) => `/analysis/${encodeURIComponent(vendor)}/${id}/consolidated-analysis`,
};
