# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache g++ libc6-compat make python3

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
